config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # GET Actions
  get 'versions', to: 'versions#index'
  get 'dashboard', to: 'dashboard#index'
  get 'admin/dashboard'

  resources :rooms do
    resources :messages
    collection do
      post :search
    end
  end

  # leave_room_path(room)
  get 'rooms/leave/:id', to: 'rooms#leave', as: 'leave_room'
  # join_room_path(room)
  get 'rooms/join/:id', to: 'rooms#join', as: 'join_room'

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get 'user/:id', to: 'users#show', as: 'user'
  # Defines the root path route ("/")
  root 'pages#home'
end

app/views/shared/_links.html.erb
<a class="nav-link py-2 px-0 px-lg-2 d-flex" href="https://github.com/mike-koala-bear/turbochatter" target="_blank" rel="noopener">
  <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" class="navbar-nav-svg" viewBox="0 0 512 499.36" role="img">
    <title>GitHub</title>
    <path fill="currentColor" fill-rule="evenodd" d="M256 0C114.64 0 0 114.61 0 256c0 113.09 73.34 209 175.08 242.9 12.8 2.35 17.47-5.56 17.47-12.34 0-6.08-.22-22.18-.35-43.54-71.2 15.49-86.2-34.34-86.2-34.34-11.64-29.57-28.42-37.45-28.42-37.45-23.27-15.84 1.73-15.55 1.73-15.55 25.69 1.81 39.21 26.38 39.21 26.38 22.84 39.12 59.92 27.82 74.5 21.27 2.33-16.54 8.94-27.82 16.25-34.22-56.84-6.43-116.6-28.43-116.6-126.49 0-27.95 10-50.8 26.35-68.69-2.63-6.48-11.42-32.5 2.51-67.75 0 0 21.49-6.88 70.4 26.24a242.65 242.65 0 0 1 128.18 0c48.87-33.13 70.33-26.24 70.33-26.24 14 35.25 5.18 61.27 2.55 67.75 16.41 17.9 26.31 40.75 26.31 68.69 0 98.35-59.85 120-116.88 126.32 9.19 7.9 17.38 23.53 17.38 47.41 0 34.22-.31 61.83-.31 70.23 0 6.85 4.61 14.81 17.6 12.31C438.72 464.97 512 369.08 512 256.02 512 114.62 397.37 0 256 0z"></path>
  </svg>
  <small class="d-lg-none ms-2">GitHub</small>
</a>

app/views/shared/_message_error.html.erb
<% if defined?(message) %>
  <div class="message-error alert-error message-error-fade">
    <div class="message-error-text center-block">
      <%= message %>
    </div>
  </div>
<% end %>

app/views/shared/_version_dropdown.html.erb
<% current_version = '1.3.8' %>
<% short_current_version = '1.3' %>
<li class="nav-item dropdown show d-flex">
    <a class="nav-item nav-link dropdown-toggle mr-md-2" href="#" id="bd-versions" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
        <%= current_version %>
    </a>
    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="bd-versions">
        <a class="dropdown-item active" href="/">Latest (<%= short_current_version %>.x)</a>
        <a class="dropdown-item" href="https://github.com/mike-koala-bear/turbochatter/releases/tag/v1.3.8">Latest Github version</a>
        <a class="dropdown-item" href="https://github.com/mike-koala-bear/turbochatter/releases/tag/v1.1.0">v1.1.0</a>
        <a class="dropdown-item" href="https://github.com/mike-koala-bear/turbochatter/releases/tag/v0.7.6-beta">v0.7.6 Beta</a>
        <hr class="dropdown-divider">
        <a class="dropdown-item" href="https://github.com/mike-koala-bear/turbochatter/releases/tag/v0.7.6">v0.7.6</a>
        <a class="dropdown-item" href="https://github.com/mike-koala-bear/turbochatter/releases/tag/v0.5.1-beta">v0.5.1-beta</a>
        <a class="dropdown-item" href="https://github.com/mike-koala-bear/turbochatter/releases/tag/v0.5.1">v0.5.1</a>
        <hr class="dropdown-divider">
        <%= link_to 'All versions', versions_path, class: 'dropdown-item' %>
    </div>
</li>