config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # GET Actions
  get 'versions', to: 'versions#index'
  get 'dashboard', to: 'dashboard#index'
  get 'admin/dashboard'

  resources :rooms do
    resources :messages
    collection do
      post :search
    end
  end

  # leave_room_path(room)
  get 'rooms/leave/:id', to: 'rooms#leave', as: 'leave_room'
  # join_room_path(room)
  get 'rooms/join/:id', to: 'rooms#join', as: 'join_room'

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get 'user/:id', to: 'users#show', as: 'user'
  # Defines the root path route ("/")
  root 'pages#home'
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <%= link_to root_path do %>
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 36 36" style="width: 37px; margin-right: 10px">
      <path fill="#FDD888" d="M28.865 7.134c7.361 7.359 9.35 17.304 4.443 22.209-4.907 4.907-14.85 2.918-22.21-4.441-.25-.25-.478-.51-.716-.766l4.417-4.417c5.724 5.724 13.016 7.714 16.286 4.442 3.271-3.271 1.282-10.563-4.441-16.287l.022.021-.021-.022C20.104 1.331 11.154-.326 6.657 4.171 4.482 6.346 3.76 9.564 4.319 13.044c-.858-4.083-.15-7.866 2.338-10.353 4.906-4.906 14.849-2.917 22.208 4.443z"/><path fill="#FFAC33" d="M19.403 34c-.252 0-.503-.077-.719-.231l-5.076-3.641-5.076 3.641c-.433.31-1.013.31-1.443-.005-.43-.312-.611-.864-.45-1.369l1.894-6.11-5.031-3.545c-.428-.315-.605-.869-.442-1.375.165-.504.634-.847 1.165-.851l6.147-.012 2.067-5.957c.168-.504.639-.844 1.17-.844.531 0 1.002.34 1.17.844l1.866 5.957 6.347.012c.532.004 1.002.347 1.165.851.164.506-.014 1.06-.442 1.375l-5.031 3.545 1.893 6.11c.162.505-.021 1.058-.449 1.369-.217.158-.471.236-.725.236z"/>
    </svg>
    <a class="navbar-brand" href="/">Turbochatter</a>
  <% end %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="/">Home</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/rooms">Start Chatting</a>
      </li>
      <% if current_user&.admin? || current_user&.owner? %>
        <li class="nav-item">
          <%= link_to "Admin/Owner", admin_dashboard_path, class: "nav-link" %>
        </li>
      <% end %>
      <%= render 'layouts/navbar_dropdown' %>
    </ul>
    <%= render 'shared/version_dropdown' %>
    <%= render 'shared/links' %>
  </div>
</nav>

app/views/layouts/_navbar_dropdown.html.erb
<% if current_user %>
  <div class="dropdown">
    <a role="button" id="dropdownMenuLink" data-bs-toggle="dropdown" class="nav-item btn btn-blue">
      <%= current_user.username if current_user %>
      <%= image_tag(current_user.navbar_avatar, class: 'navbar-pfp') if current_user %>
    </a>
    <ul class="dropdown-menu bg-dark">
      <div>
        <div class="ml-2">
          <%= link_to "Edit Account", edit_user_registration_path %> <br>
          <%= link_to "Private chat", user_path(current_user) %>
          <p class="text-white">
            <% user_role = current_user.role %>
            <b>Role:</b> <%= link_to "#{user_role}", user_path(current_user), class: "msg-role-#{user_role}" %>
          </p>
        </div>
        <%= button_to 'Logout', destroy_user_session_path, method: :delete, class: 'btn rounded-0 w-100 logout-btn' %>
      </div>
    </ul>
  </div>
<% end %>

app/views/layouts/_new_message_form.html.erb
<div class="form-group msg-form">
  <%= form_with(model: [@single_room, @message], remote: true, class: 'd-flex',
                data: { controller: "reset-form", action: "turbo:submit-end->reset-form#reset", id: 'message-form' }) do |f| %>
    <div id="attachment-previews"
         data-controller="message-preview"
         data-action="message-preview#preview"
         class="d-none">
    </div>
    <%= content_tag :i, nil, id: 'audio-record-button', class: 'bi bi-mic microphone-icon' %>
    <div class="image-upload">
      <label for="message_attachments">
        <i class="bi bi-plus-circle upload-button"></i>
      </label>
      <%= f.file_field(:attachments, multiple: true,
                       data: { controller: "message-preview", action: "change->message-preview#preview" },
                       direct_upload: true) %>
    </div>
    <%= f.text_field :body, id: 'chat-text', class: 'form-control msg-content', autocomplete: 'off' %>
    <%= f.submit "Send",
                 data: { disable_with: false,
                         controller: "message-preview",
                         action: "click->message-preview#clearPreviews" },
                 class: 'btn btn-primary' %>
    </div>
  <% end %>
</div>

app/views/layouts/_new_room_form.html.erb
<% if current_user.admin? || current_user.owner? %>
  <%= form_with(model: @room, remote: true, class: 'd-flex',
                data: { controller: "reset-form", action: "turbo:submit-end->reset-form#reset" }) do |f| %>
    <%= f.text_field :name, class: 'form-control new-room-input', autocomplete: 'off',
                     placeholder: "Admins Only - Create Room" %>
    <%= f.submit data: { turbo: "false" }, class: "btn btn-success new-room-button" %>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Turbochatter</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <!-- Jquery Code -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <!-- Bootstrap Version 4.1.3 Javascript -->
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.3/dist/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    <!-- Bootstrap Latest Version Javascript -->
    <script src="https://cdn.usebootstrap.com/bootstrap/latest/js/bootstrap.bundle.min.js"></script>
    <!-- Bootstrap Icons -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.2/font/bootstrap-icons.css">
    <!--  Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <!-- Favicons -->
    <%= favicon_link_tag asset_path('dizzy.png') %>

    <style>
      <%= ".msg-#{current_user&.id}" %> {
        background-color: #007bff !important;
        padding: 10px;
      }
      <%= ".cont-#{current_user&.id}" %> {
        display: flex;
        justify-content: flex-end;
      }
    </style>
    <script>
        $(function () {
            $('[data-toggle="tooltip"]').tooltip()
        })
    </script>
  </head>
  <body id="bootstrap-overrides">
    <%= render 'layouts/navbar' %>
    <%= yield %>
  </body>
</html>